server:
  port: 8511

#服务器地址
ali:
  address: 47.103.107.73

spring:
  data:
    redis:
      host: ${ali.address}
      port: 6379
  application:
    name: service-product
  cloud:
    nacos:
      discovery:
        server-addr: ${ali.address}:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ali.address}:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml